services:
  - type: web
    name: linkedin-clone
    env: node
    buildCommand: npm ci && cd server && npm ci && cd ../linkedin-frontend && npm ci && npm run build
    startCommand: cd server && npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0