services:
  - type: web
    name: linkedin-clone
    env: node
    buildCommand: cd linkedin-frontend && npm install && npm run build
    startCommand: node server/src/index.js
    envVars:
      - key: NODE_VERSION
        value: 18.17.0